name: Deploy DMS to GCE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
            
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}

      - name: Deploy container on GCE
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            docker rm timewise-dms --force || true
            docker run \
              --name timewise-dms \
              -dp 8089:8089 \
              -e ENV=production \
              --restart always \
              -v /home/khanhhn.hoang/env_files/.dms_env:/.env \
              ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          EOF
